<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    /**
     * @param $limit
     *
     * @return array
     */
    public function getIndexArticles($limit) : array
    {
        $qb = $this->createQueryBuilder('a');
        $qb->leftJoin('a.user', 'user')
                ->addSelect('user')
                ->orderBy('a.createdAt', 'DESC')
                ->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }
}
