<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    /**
     * @param $limit
     *
     * @return array
     */
    public function getIndexArticles($limit) : array
    {
        $qb = $this->createQueryBuilder('a');
        $qb->leftJoin('a.user', 'user')
                ->addSelect('user')
                ->orderBy('a.createdAt', 'DESC')
                ->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }

    /**
     * @param $page
     * @param $nbPerPage
     *
     * @return Paginator
     */
    public function getArticles($page, $nbPerPage) : Paginator
    {
        $query = $this->createQueryBuilder('a')
                ->leftJoin('a.user', 'usr')
                ->addSelect('usr')
                ->orderBy('a.createdAt', 'DESC')
                ->getQuery();

        $query
                ->setFirstResult(($page-1) * $nbPerPage)
                ->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }
}
