<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * @param $status
     *
     * @return array
     */
    public function getComsBy($status) : array
    {
        $qb = $this->createQueryBuilder('c');
        $qb ->where('c.'.$status.' = :key')
                ->setParameter('key', true)
                ->leftJoin('c.article', 'art')
                ->addSelect('art');

        return $qb->getQuery()->getResult();
    }

    /**
     * @return array
     */
    public function getAll() : array
    {
        $qb = $this->createQueryBuilder('c')
                ->leftJoin('c.article', 'art')
                ->addSelect('art');

        return $qb->getQuery()->getResult();
    }
}
