<?php

namespace AppBundle\Repository;

/**
 * TaxrefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLast()
    {
        $qb = $this->createQueryBuilder('t')
            ->orderBy('t.updateAt','DESC')
            ->setMaxResults(1)
            ;

        return $qb->getQuery()->getOneOrNullResult();

    }


}
