<?php

namespace AppBundle\Repository;

/**
 * TaxrefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLast()
    {
        $qb = $this->createQueryBuilder('t')
            ->where('t.isUpdate = 0')
            ->orderBy('t.updateAt', 'DESC')
            ->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }


    public function getLastUpdate()
    {
        $qb = $this->createQueryBuilder('t')
            ->where('t.isUpdate = 1')
            ->orderBy('t.updateAt', 'DESC')
            ->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
