<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsers() : array
    {
        $qb = $this->createQueryBuilder('u')
                ->leftJoin('u.observations', 'obs')
                ->addSelect('obs')
                ->orderBy('u.id', 'DESC')
                ->getQuery();

        return $qb->getResult();
    }
}
