imports:
    - { resource: "@AppBundle/Resources/config/security.yml" }

security:
    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_NATURALIST:  ROLE_USER
        ROLE_EDITOR:      ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_NATURALIST, ROLE_EDITOR]

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ajouter-observation, role: ROLE_USER }
        - { path: ^/admin/ajouter-article, role: ROLE_EDITOR }
        - { path: ^/admin, role: ROLE_USER }

