# src/AppBundle/Resources/config/services.yml



services:
    parse_file_csv:
        class: AppBundle\Service\ParseFileCSV

    check_file:
        class: AppBundle\Service\CheckFileUpload

    observation_mailer:
        class: AppBundle\Service\ObservationMailer
        arguments:
            - "@mailer"
            - "@templating"

    doctrine_listener.observationAdd:
        class: AppBundle\DoctrineListener\ObservationAddListener
        arguments:
            - "@observation_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }


    user_mailer:
        class: AppBundle\Service\UserMailer
        arguments:
            - "@mailer"
            - "@templating"

    doctrine_listener.userAdd:
        class: AppBundle\DoctrineListener\UserAddListener
        arguments:
            - "@user_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }